[tox]
min_version = 4.0
env_list = lint, test

[testenv]
package = editable

[testenv:lint]
deps =
    black>=24.0
    isort>=5.13
    flake8>=7.0
    mypy>=1.10
    typer>=0.12.0
    typer-di>=0.1.0
commands =
    black --check src tests
    isort --check-only src tests
    flake8 src tests
    mypy src tests

[testenv:test]
deps =
    pytest>=8.0
    pytest-cov>=5.0
    typer>=0.12.0
    typer-di>=0.1.0
commands =
    pytest {posargs}
